//! Snowball stopword lists for the languages the BM25 analyzer stems.
//!
//! Embedded rather than pulled from a crate: the lists are small, they must never
//! change under a published index (a different list silently changes recall), and
//! the wheel has a hard size budget enforced in CI.
//!
//! Source: the Snowball project's stopword lists (BSD-licensed), trimmed to the
//! bare function words. Callers can replace any of them at open time.

/// Stopwords for `language`, or `None` when the language has no bundled list.
pub fn for_language(language: &str) -> Option<&'static [&'static str]> {
    match language {
        "english" => Some(ENGLISH),
        "french" => Some(FRENCH),
        "german" => Some(GERMAN),
        "spanish" => Some(SPANISH),
        "portuguese" => Some(PORTUGUESE),
        _ => None,
    }
}

pub const ENGLISH: &[&str] = &[
    "a",
    "about",
    "above",
    "after",
    "again",
    "against",
    "all",
    "am",
    "an",
    "and",
    "any",
    "are",
    "aren't",
    "as",
    "at",
    "be",
    "because",
    "been",
    "before",
    "being",
    "below",
    "between",
    "both",
    "but",
    "by",
    "can't",
    "cannot",
    "could",
    "couldn't",
    "did",
    "didn't",
    "do",
    "does",
    "doesn't",
    "doing",
    "don't",
    "down",
    "during",
    "each",
    "few",
    "for",
    "from",
    "further",
    "had",
    "hadn't",
    "has",
    "hasn't",
    "have",
    "haven't",
    "having",
    "he",
    "her",
    "here",
    "hers",
    "herself",
    "him",
    "himself",
    "his",
    "how",
    "i",
    "if",
    "in",
    "into",
    "is",
    "isn't",
    "it",
    "its",
    "itself",
    "let",
    "me",
    "more",
    "most",
    "mustn't",
    "my",
    "myself",
    "no",
    "nor",
    "not",
    "of",
    "off",
    "on",
    "once",
    "only",
    "or",
    "other",
    "ought",
    "our",
    "ours",
    "ourselves",
    "out",
    "over",
    "own",
    "same",
    "shan't",
    "she",
    "should",
    "shouldn't",
    "so",
    "some",
    "such",
    "than",
    "that",
    "the",
    "their",
    "theirs",
    "them",
    "themselves",
    "then",
    "there",
    "these",
    "they",
    "this",
    "those",
    "through",
    "to",
    "too",
    "under",
    "until",
    "up",
    "very",
    "was",
    "wasn't",
    "we",
    "were",
    "weren't",
    "what",
    "when",
    "where",
    "which",
    "while",
    "who",
    "whom",
    "why",
    "with",
    "won't",
    "would",
    "wouldn't",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
];

pub const FRENCH: &[&str] = &[
    "au", "aux", "avec", "ce", "ces", "dans", "de", "des", "du", "elle", "en", "et", "eux", "il",
    "ils", "je", "la", "le", "les", "leur", "lui", "ma", "mais", "me", "meme", "mes", "moi", "mon",
    "ne", "nos", "notre", "nous", "on", "ou", "par", "pas", "pour", "qu", "que", "qui", "sa", "se",
    "ses", "son", "sur", "ta", "te", "tes", "toi", "ton", "tu", "un", "une", "vos", "votre",
    "vous", "c", "d", "j", "l", "m", "n", "s", "t", "y", "est", "ete", "etre", "avoir", "cette",
    "sont",
];

pub const GERMAN: &[&str] = &[
    "aber", "alle", "als", "also", "am", "an", "auch", "auf", "aus", "bei", "bin", "bis", "bist",
    "da", "dann", "das", "dass", "dein", "der", "den", "des", "dem", "die", "dies", "diese",
    "doch", "dort", "du", "durch", "ein", "eine", "einem", "einen", "einer", "eines", "er", "es",
    "euer", "eure", "fur", "hab", "habe", "haben", "hat", "hatte", "hier", "ich", "ihr", "im",
    "in", "ist", "ja", "jede", "jetzt", "kann", "kein", "man", "mein", "mit", "muss", "nach",
    "nicht", "noch", "nun", "nur", "ob", "oder", "sein", "sich", "sie", "sind", "so", "uber", "um",
    "und", "uns", "unser", "vom", "von", "vor", "war", "waren", "was", "weg", "weil", "wenn",
    "werden", "wie", "wir", "wird", "wo", "zu", "zum", "zur",
];

pub const SPANISH: &[&str] = &[
    "a", "al", "algo", "ante", "antes", "como", "con", "contra", "cual", "cuando", "de", "del",
    "desde", "donde", "dos", "el", "ella", "ellos", "en", "entre", "era", "eres", "es", "esa",
    "ese", "eso", "esta", "estan", "este", "esto", "ha", "hasta", "hay", "la", "las", "le", "les",
    "lo", "los", "mas", "me", "mi", "mucho", "muy", "nada", "ni", "no", "nos", "o", "otra", "otro",
    "para", "pero", "poco", "por", "porque", "que", "quien", "se", "sea", "si", "sin", "sobre",
    "son", "su", "sus", "también", "tambien", "te", "tiene", "todo", "tu", "un", "una", "uno", "y",
    "ya", "yo",
];

pub const PORTUGUESE: &[&str] = &[
    "a", "ao", "aos", "as", "com", "como", "da", "das", "de", "dela", "dele", "depois", "do",
    "dos", "e", "ela", "elas", "ele", "eles", "em", "entre", "era", "essa", "esse", "esta", "este",
    "eu", "foi", "for", "isso", "isto", "ja", "lhe", "mais", "mas", "me", "mesmo", "meu", "minha",
    "muito", "na", "nao", "nas", "nem", "no", "nos", "nossa", "nosso", "num", "numa", "o", "os",
    "ou", "para", "pela", "pelo", "por", "qual", "quando", "que", "quem", "se", "sem", "ser",
    "seu", "sua", "so", "sao", "tambem", "te", "tem", "tu", "um", "uma", "voce", "vos",
];
